### ISSUE TITLE
Question from newbie

### ISSUE THREAD

**Issue by Jippy1971** [tinkersprojects/RGB_LED#5]
Hello,
I'm looking for an ESPEasy plugin (for my WEMOS D1) that can be used to control a 4-pin RGB LED. While searching I found your plugin.
Since I'm an absolute newbie in this area, I wanted to ask if I can use your plugin for this case?
I've also managed (at least I think so) to integrate the plugin into an ESPEasy-mega image. To do this, I selected your plugin in Platform IO under Libraries, assigned it to the project and then started the build process. Then I flashed the new image to the WEMOS. However, I don't see any new options for an RGB LED under "Devices", or to specify the pins.
My questions now, do I understand something wrong, do I something wrong, does no new entry appear under "Devices" or where can I define the 4 pins?
I hope I write not too confusing and that you understand my problem.

Best regards
Uwe

**Comment by tinkersprojects** [comment]
hey mate, sorry for the late reply.
what do you mean by 4 Pins? are you wanting to use a RGBW LED (1 pin for each colour)
pin are declared up the top of the program:
`RGB_LED LED(9,10,11);`
where 9,10,11 are the RGB pins, 9 is Red pin, 10 is Blue pin and 11 is Green Pin.

**Comment by Jippy1971** [comment]
Hey,

ok, I thought a new device would appear in the ESPEasy Mega Image when I flashed it to the WEMOS.

Thanks.

Best regards
Uwe
